### ISSUE TITLE
Feil ved henting/visning av lenke og tittel til artikkel

### ISSUE THREAD

**Issue by nordmoen** [navikt/nks-bob-frontend#29]
Spurte Bob om dagpenger og sykepenger og fikk da feilmelding om at den ikke kunne finne lenke til artikkel:
![image](https://github.com/user-attachments/assets/bb60f0bc-c12d-4cad-a5c2-70ea9587bac6)

KBS-en skal svare ut riktig på dette så jeg tror det er en feil i logikken for å hente ut lenke fra metadata.

![image](https://github.com/user-attachments/assets/7a3db93b-d09a-4dd5-84ba-389d27973d4e)

Siden det er identisk sitat så antar jeg at det skulle vært samme artikkel som på Slack.

**Comment by Bendixx** [comment]
Jeg får ikke fremprovosert feilen igjen. Mulig at frontend feilet pga. feil med henting av metadata? 

Hvis du ser feilen igjen, kunne du også sendt ved response-data?

**Comment by nordmoen** [comment]
Godt mulig dette er fikset nå, dere har jo gjort mye i det siste. Jeg foreslår å lukke og heller gjenåpne hvis noen veiledere kommer over det samme 👍
