### ISSUE TITLE
Feil ved generering av `textStart` og `textEnd` i URL for text fragment

### ISSUE THREAD

**Issue by nordmoen** [navikt/nks-bob-frontend#30]
Det er nok en bug når det er lite tekst i sitatet. Da blir det overlapp mellom `textStart` og `textEnd`.

Eksempel:
![image](https://github.com/user-attachments/assets/6cc34dd2-7410-4ca9-a86f-e26fcc22879f)

URL blir `https://data.ansatt.nav.no/quarto/e7b3e02a-0c45-4b5c-92a2-a6d364120dfb/Dagpenger/kA02o000000M7NwCAK.html#til-bruker#:~:text=I%20Norge%20kaller%20vi,vi%20arbeidsledighetstrygd%20for%20dagpenger` Legg merke til `vi, vi` som gjør at det ikke fungerer.

I Slack boten så har jeg dette:
```python
    cite_words = cite_text.replace("\n", " ").split(" ")
    # Pass på at det ikke er overlapp i korte siteringer
    num_word = min(num_word, len(cite_words) // 2)
    # Hvis det er for få ord så gjør vi heller ikke noe
    if num_word < 1:
        return base_url
    start_fragment = " ".join(cite_words[:num_word])
    end_fragment = " ".join(cite_words[-num_word:])
```
Hvor `num_word` er antall ord å ta med i `textStart` og `textEnd` (default satt til `num_word = 4`)

**Comment by Bendixx** [comment]
Det er samme logikk i frontend, hvor den bruker de 4 første- og siste ordene i citation. Jeg ser det er 7 ord i citation du viser til, så problemet her er vel muligens at den da gjentar det fjerde ordet for textEnd (vi, vi).

Tar de 3 første og 3 siste ordene som en midlertidig fix.

**Comment by nordmoen** [comment]
Jeg ville foreslå å heller gjøre `num_word = min(num_word, len(cite_words) // 2)` altså å ta det minste av antall ord (f.eks. 4) og antall ord i siteringen delt på 2 rundet ned. Da tar du 4 ord når setninger er lange nok, men for kortere setninger så tar du færre.

Hvis man ikke legger til en slik taktikk så vil problemet oppstå hvis det finnes setninger som har færre enn 6 ord, osv.

**Comment by nordmoen** [comment]
Kom akkurat over en text fragment som viser at 3 ord nok er litt lite: https://data.ansatt.nav.no/quarto/e7b3e02a-0c45-4b5c-92a2-a6d364120dfb/Foreldre%20og%20svangerskapspenger/kA07U0000004GMYSA2.html#til-bruker#:~:text=Hvis%20du%20har,i%20din%20sak.

**Comment by Bendixx** [comment]
Da skal denne være i orden (om jeg ikke har oversett noe... haha). 

` 
  const citeWords = citation.text.replace("\n", "").split(" ")
  const numWords = Math.min(citeWords.length / 2, 6)
  const textStart = citeWords.slice(0, numWords).join(" ")
  const textEnd = citeWords.slice(numWords).join(" ")
  `
  
numWords er antall ord i citeWords / 2, men begrenses til maks 6 ord. Tenker vi tester litt med det for å se om det gir bra utslag for nå.

`
numWords < 1
                ? `${matchingContextCitationData.KnowledgeArticle_QuartoUrl}`
                : `${matchingContextCitationData.KnowledgeArticle_QuartoUrl}#:~:text=${encodeURIComponent(textStart)},${encodeURIComponent(textEnd)}`
`

Den siste snutten her viser at numWords inneholder færre enn 1 ord vises "base_url".

Jeg ser at punktlister og lignende ikke kommer med. Jeg skal prøve å tweake videre for å sikre at vi fanger opp alt vi har mulighet til å fange opp med denne metoden.
