### ISSUE TITLE
Feil ved generering av text fragment, kombinerer to URL fragmenter

### ISSUE THREAD

**Issue by nordmoen** [navikt/nks-bob-frontend#31]
Ref #30 

Hvis man ser i URL-en der så kombineres to URL fragmenter, dette er ikke tillat i forhold til [standarden](https://developer.mozilla.org/en-US/docs/Web/URI/Fragment), men jeg ser at det fungerer i praksis 🤷 

URL-en det er snakk om `https://data.ansatt.nav.no/quarto/e7b3e02a-0c45-4b5c-92a2-a6d364120dfb/Dagpenger/kA02o000000M7NwCAK.html#til-bruker#:~:text=I%20Norge%20kaller%20vi,vi%20arbeidsledighetstrygd%20for%20dagpenger`

**Comment by Bendixx** [comment]
Dette ble fikset i https://github.com/navikt/nks-bob-frontend/issues/30. Nå vil ikke ord bli gjentatt: https://github.com/navikt/nks-bob-frontend/issues/30
