### ISSUE TITLE
Potensiell bug ved erstatting av `\n` i sitattekst

### ISSUE THREAD

**Issue by nordmoen** [navikt/nks-bob-frontend#33]
https://github.com/navikt/nks-bob-frontend/blob/63e5d092774c3c231efdd9d37e9020e0c442ec86/src/components/content/chat/chatbubbles/BobAnswerCitations.tsx#L26

Når man erstatter `\n` i teksten med en tom streng (e.g. `""`) så kan det føre til at ord bli slått sammen.

Jeg tror det er bedre å erstatte med mellomrom (e.g. `" "`). Dette kan gi tomme strenger når man splitter på mellomrom, men de kan enkelt filtreres ut (i motsetning til ord som slåes sammen som er vanskelige å oppdage og dele korrekt).

**Comment by Bendixx** [comment]
Fixed :) https://github.com/navikt/nks-bob-frontend/commit/d6453eafe9c3c4b6cb503ae02719c63864cd38dc
